/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "tr" | "en" | "nl" | "ar";

export const languages: Record<Language, { name: string; flag: string }> = {
  tr: { name: "Türkçe", flag: "🇹🇷" },
  en: { name: "English", flag: "🇬🇧" },
  nl: { name: "Nederlands", flag: "🇳🇱" },
  ar: { name: "العربية", flag: "🇸🇦" },
};

export const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Auth
    "auth.login": "Hesabınıza giriş yapın",
    "auth.signup": "Yeni hesap oluşturun",
    "auth.fullName": "Ad Soyad",
    "auth.fullNamePlaceholder": "Adınız Soyadınız",
    "auth.email": "E-posta",
    "auth.emailPlaceholder": "ornek@email.com",
    "auth.password": "Şifre",
    "auth.loginButton": "Giriş Yap",
    "auth.signupButton": "Kayıt Ol",
    "auth.noAccount": "Hesabınız yok mu? Kayıt olun",
    "auth.hasAccount": "Zaten hesabınız var mı? Giriş yapın",
    "auth.signupSuccess": "Kayıt başarılı",
    "auth.loginSuccess": "Giriş başarılı",
    "auth.welcome": "Hoş Geldiniz",
    "auth.lang_code": "tr",
    "auth.checkEmail": "E-posta adresinizi doğrulamak için gelen kutunuzu kontrol edin.",
    "auth.error": "Hata",
    "landing.title": "Sahadan Alınan Veriler",
    "landing.highlight": "Tek Tıkla Raporunuz",
    "landing.badge": "Dijital Raporlama Sistemi",
    "landing.description": "EA APP, sahadaki günlük çalışma saatlerinizi, personelinizi ve ek işlerinizi (meerwerk) dijital ortamda kaydetmenizi sağlar. Girdiğiniz verileri otomatik olarak hesaplayıp anında PDF formatında profesyonel haftalık raporlara dönüştürür.",
    "landing.secure": "Güvenli Veri Depolama",
    "landing.access": "Her Yerden Erişim",
    "feature.1.title": "Kolay Veri Girişi",
    "feature.1.desc": "Günlük mesaileri, konumları ve personellerinizi saniyeler içinde kaydedin.",
    "feature.2.title": "Otomatik PDF",
    "feature.2.desc": "Verileriniz, Hollandaca hazır bir şekilde resmi PDF raporları olarak oluşturulur.",
    "feature.3.title": "Bulut Kaydı",
    "feature.3.desc": "Kayıt silinmesi veya dosya kayıplarını unutun. Tüm raporlarınız ve fotoğraflarınız güvenle saklanır.",

    // Index
    "index.admin": "Yönetici Paneli",
    "index.activities": "Kayıt Bulundu",
    "index.new": "Yeni Rapor",
    "index.newActivity": "Yeni Haftalık Çalışma Raporu",



    // Activity Form
    "form.whatDidYouDo": "Yapılan İşlemin Detayı",
    "form.descriptionPlaceholder": "Gerçekleştirilen işleri profesyonel bir dille açıklayın...",
    "form.location": "Çalışma Sahası",
    "form.locationPlaceholder": "Örn. Amsterdam, Kinkerstraat Şantiyesi",
    "form.date": "Rapor Haftası",
    "form.selectDate": "Başlangıç Tarihi Seçin",
    "form.photos": "Saha Fotoğrafları",
    "form.photo": "Görsel",
    "form.upload": "Dosya Yükle",
    "form.addActivity": "Raporu Kaydet",
    "form.weeklyWork": "Haftalık Mesai",
    "form.hours": "Süre",
    "form.hoursPlaceholder": "Saat",
    "form.totalHours": "Toplam Çalışma Süresi",
    "form.teammates": "Ekip Arkadaşları",
    "form.person": "Personel",
    "form.personName": "İsim Soyisim",
    "form.addPerson": "Personel Ekle",
    "form.meerwerk": "İlave Çalışmalar (Meerwerk)",
    "form.meerwerkPlaceholder": "Varsa ekstra talepleri belirtin...",

    // Days
    "days.monday": "Pazartesi",
    "days.tuesday": "Salı",
    "days.wednesday": "Çarşamba",
    "days.thursday": "Perşembe",
    "days.friday": "Cuma",
    "days.saturday": "Cumartesi",
    "days.workPlaceholder": "Bu gün ne yaptınız?",

    // Activity List
    "list.loading": "Aktiviteler yükleniyor...",
    "list.empty": "Henüz aktivite eklenmedi",
    "list.addFirst": "Yukarıdan ilk aktivitenizi ekleyin",
    "list.photos": "fotoğraf",
    "list.photo": "Fotoğraf",
    "list.weekOf": "Hafta",
    "list.hoursShort": "saat",
    "list.translating": "Çevriliyor...",

    // Invoice
    "invoice.title": "Haftalık Çalışma",
    "invoice.generateInvoice": "Rapor Oluştur",
    "invoice.weeklyReport": "Haftalık Çalışma Raporu",
    "invoice.employee": "Hazırlayan",
    "invoice.period": "Dönem",
    "invoice.day": "Gün",
    "invoice.description": "Açıklama",
    "invoice.location": "Konum",
    "invoice.hours": "Saat",
    "invoice.total": "Toplam",
    "invoice.print": "Yazdır",
    "invoice.send": "Gönder",
    "invoice.saveToPhone": "Telefona Kaydet",
    "invoice.sendEmail": "E-posta Gönder",
    "invoice.sendWhatsApp": "WhatsApp ile Gönder",
    "invoice.pdfDownloaded": "PDF dosyası indirildi, lütfen e-postaya ekleyin.",

    // Edit
    "edit.title": "Aktiviteyi Düzenle",
    "edit.save": "Kaydet",
    "edit.cancel": "İptal",
    "edit.success": "Aktivite güncellendi",
    "invoice.close": "Kapat",

    // Translate
    "translate.button": "Çevir",
    "translate.translating": "Çevriliyor...",
    "translate.error": "Çeviri başarısız oldu",
    "translate.rateLimited": "Çok fazla istek. Lütfen bekleyin.",
    "translate.paymentRequired": "Kredi gerekli.",

    // Forgot Password
    "auth.forgotPassword": "Şifrenizi mi unuttunuz?",
    "auth.sendResetLink": "Sıfırlama Linki Gönder",
    "auth.backToLogin": "Giriş sayfasına dön",
    "auth.resetEmailSent": "E-posta gönderildi",
    "auth.checkEmailReset": "Şifre sıfırlama linki için gelen kutunuzu kontrol edin.",
    "auth.newPassword": "Yeni Şifre",
    "auth.confirmNewPassword": "Yeni Şifre Tekrar",
    "auth.setNewPassword": "Yeni Şifre Belirle",
    "auth.updatePasswordButton": "Şifreyi Güncelle",
    "auth.passwordUpdated": "Şifre başarıyla güncellendi",
    "auth.passwordUpdateError": "Şifre güncellenemedi",

    // Error messages
    "auth.invalidCredentials": "E-posta veya şifre hatalı",
    "auth.userNotFound": "Bu e-posta ile kayıtlı kullanıcı bulunamadı",
    "auth.emailNotConfirmed": "E-posta adresiniz henüz doğrulanmadı. Lütfen gelen kutunuzu kontrol edin.",
    "auth.tooManyRequests": "Çok fazla deneme yaptınız. Lütfen biraz bekleyin.",
    "auth.weakPassword": "Şifre en az 6 karakter olmalıdır",
    "auth.invalidEmail": "Geçersiz e-posta adresi",
    "auth.userAlreadyExists": "Bu e-posta adresi zaten kayıtlı. Giriş yapmayı veya şifre sıfırlamayı deneyin.",
    "auth.accountBlocked": "Hesabınız engellenmiştir. Yönetici ile iletişime geçin.",
    "auth.confirmPassword": "Şifre Tekrar",
    "auth.passwordMismatch": "Şifreler eşleşmiyor",

    // Admin Panel
    "adminPanel.title": "Yönetici Paneli",
    "adminPanel.users": "kullanıcı",
    "adminPanel.addUser": "Kullanıcı Ekle",
    "adminPanel.addUserTitle": "Yeni Kullanıcı Ekle",
    "adminPanel.addUserDesc": "Yeni bir personel hesabı oluşturun.",
    "adminPanel.name": "İsim",
    "adminPanel.role": "Rol",
    "adminPanel.status": "Durum",
    "adminPanel.actions": "İşlemler",
    "adminPanel.staff": "Personel",
    "adminPanel.blocked": "Engelli",
    "adminPanel.active": "Aktif",
    "adminPanel.delete": "Sil",
    "adminPanel.deleteConfirmTitle": "Kullanıcıyı Sil",
    "adminPanel.deleteConfirmDesc": "{name} kullanıcısını silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    "adminPanel.userAdded": "Kullanıcı başarıyla eklendi",
    "adminPanel.userDeleted": "Kullanıcı başarıyla silindi",
    "adminPanel.userBlocked": "Kullanıcı engellendi",
    "adminPanel.userUnblocked": "Kullanıcı engeli kaldırıldı",
    "admin.allUsers": "Tüm Kullanıcılar",
    "footer.rights": "Tüm Hakları Saklıdır",
    "adminPanel.fetchError": "Kullanıcılar yüklenemedi",
    "adminPanel.addError": "Kullanıcı eklenemedi",
    "adminPanel.deleteError": "Kullanıcı silinemedi",
    "adminPanel.blockError": "İşlem başarısız oldu",
    "adminPanel.fillAllFields": "Lütfen tüm alanları doldurun",
    "adminPanel.adminAssigned": "Kullanıcı admin yapıldı",
    "adminPanel.adminRemoved": "Admin yetkisi kaldırıldı",
    "adminPanel.userOpened": "Kullanıcı açıldı",
    "error.404": "Hata! Sayfa bulunamadı",
    "error.returnHome": "Ana Sayfaya Dön",

    // Activity Card & Form
    "activity.workReport": "HAFTALIK ÇALIŞMA RAPORU",
    "activity.preparedBy": "Hazırlayan",
    "activity.supervisor": "Saha Sorumlusu (Şef)",
    "activity.period": "Rapor Dönemi",
    "activity.day": "İş Günü",
    "activity.description": "İş Detayı",
    "activity.extraWork": "İlave İşler (Meerwerk)",
    "activity.location": "Saha / Konum",
    "activity.hours": "Mesai",
    "activity.details": "Çalışma Detayları",
    "activity.gallery": "Fotoğraf Galerisi",
    "activity.subtitle": "Haftalık çalışma özeti günlüğü",
    "activity.send": "GÖNDER",
    "activity.edit": "DÜZENLE",
    "activity.delete": "SİSTEMDEN SİL",
    "activity.total": "Genel Toplam",
    "activity.save": "Raporu Kaydet",
    "activity.saved": "Başarıyla Kaydedildi",
    "activity.saving": "Veriler İşleniyor...",
    "activity.add": "Yeni Kayıt",
    "activity.photo": "FOTOĞRAF",
    "activity.submit": "OPSLAAN",
    "activity.locationDetected": "Konum Doğrulandı",
    "activity.totalRecords": "Toplam {count} Rapor",
    "activity.week": "Hafta no",
    "activity.error": "Rapor oluşturulurken bir hata oluştu.",
    "activity.locationPermissionRequired": "Konum izni reddedildi. Lütfen cihazınızın konum (GPS) özelliğini açın ve tarayıcı ayarlarından bu siteye konum izni verin.",
  },
  en: {
    // Auth
    "auth.login": "Login to your account",
    "auth.signup": "Create a new account",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Your Full Name",
    "auth.email": "Email",
    "auth.emailPlaceholder": "example@email.com",
    "auth.password": "Password",
    "auth.loginButton": "Login",
    "auth.signupButton": "Sign Up",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Login",
    "auth.signupSuccess": "Sign up successful",
    "auth.loginSuccess": "Login successful",
    "auth.welcome": "Welcome",
    "auth.lang_code": "en",
    "auth.checkEmail": "Check your inbox to verify your email address.",
    "auth.error": "Error",
    "landing.title": "Data from the Field",
    "landing.highlight": "Your Report in One Click",
    "landing.badge": "Digital Reporting System",
    "landing.description": "EA APP allows you to digitally record your daily work hours, staff, and extra work (meerwerk) directly from the field. It automatically calculates the data and instantly turns them into professional weekly PDF reports.",
    "landing.secure": "Secure Data Storage",
    "landing.access": "Access Anywhere",
    "feature.1.title": "Easy Data Entry",
    "feature.1.desc": "Log daily shifts, locations, and your team members in seconds.",
    "feature.2.title": "Automated PDF",
    "feature.2.desc": "Your data is instantly generated as official PDF reports, completely in Dutch.",
    "feature.3.title": "Cloud Saving",
    "feature.3.desc": "Forget about deleted records or lost files. All your reports and photos are securely stored.",

    // Index
    "index.admin": "Admin",
    "index.activities": "activities",
    "index.new": "New",
    "index.newActivity": "New Weekly Activity",



    // Activity Form
    "form.whatDidYouDo": "What did you do?",
    "form.descriptionPlaceholder": "Describe your work...",
    "form.location": "Location",
    "form.locationPlaceholder": "e.g. Main Office, Amsterdam",
    "form.date": "Week Starting",
    "form.selectDate": "Select date",
    "form.photos": "Photos",
    "form.photo": "Photo",
    "form.upload": "Upload",
    "form.addActivity": "Add Weekly Activity",
    "form.weeklyWork": "Weekly Work",
    "form.hours": "Hours",
    "form.hoursPlaceholder": "Hours",
    "form.totalHours": "Total Hours",
    "form.teammates": "Teammates",
    "form.person": "Person",
    "form.personName": "Name",
    "form.addPerson": "Add Person",
    "form.meerwerk": "Extra Work",
    "form.meerwerkPlaceholder": "Extra work if any...",

    // Days
    "days.monday": "Monday",
    "days.tuesday": "Tuesday",
    "days.wednesday": "Wednesday",
    "days.thursday": "Thursday",
    "days.friday": "Friday",
    "days.saturday": "Saturday",
    "days.workPlaceholder": "What did you do this day?",

    // Activity List
    "list.loading": "Loading activities...",
    "list.empty": "No activities yet",
    "list.addFirst": "Add your first activity above",
    "list.photos": "photos",
    "list.photo": "Photo",
    "list.weekOf": "Week of",
    "list.hoursShort": "hours",
    "list.translating": "Translating...",

    // Invoice
    "invoice.title": "Weekly Work",
    "invoice.generateInvoice": "Generate Report",
    "invoice.weeklyReport": "Weekly Work Report",
    "invoice.employee": "Employee",
    "invoice.period": "Period",
    "invoice.day": "Day",
    "invoice.description": "Description",
    "invoice.location": "Location",
    "invoice.hours": "Hours",
    "invoice.total": "Total",
    "invoice.print": "Print",
    "invoice.send": "Send",
    "invoice.saveToPhone": "Save to Phone",
    "invoice.sendEmail": "Send via Email",
    "invoice.sendWhatsApp": "Send via WhatsApp",
    "invoice.pdfDownloaded": "PDF file downloaded, please attach it to the email.",

    // Edit
    "edit.title": "Edit Activity",
    "edit.save": "Save",
    "edit.cancel": "Cancel",
    "edit.success": "Activity updated",
    "invoice.close": "Close",

    // Translate
    "translate.button": "Translate",
    "translate.translating": "Translating...",
    "translate.error": "Translation failed",
    "translate.rateLimited": "Too many requests. Please wait.",
    "translate.paymentRequired": "Credits required.",

    // Forgot Password
    "auth.forgotPassword": "Forgot your password?",
    "auth.sendResetLink": "Send Reset Link",
    "auth.backToLogin": "Back to login",
    "auth.resetEmailSent": "Email sent",
    "auth.checkEmailReset": "Check your inbox for the password reset link.",
    "auth.newPassword": "New Password",
    "auth.confirmNewPassword": "Confirm New Password",
    "auth.setNewPassword": "Set New Password",
    "auth.updatePasswordButton": "Update Password",
    "auth.passwordUpdated": "Password updated successfully",
    "auth.passwordUpdateError": "Failed to update password",

    // Error messages
    "auth.invalidCredentials": "Invalid email or password",
    "auth.userNotFound": "No user found with this email",
    "auth.emailNotConfirmed": "Your email has not been verified yet. Please check your inbox.",
    "auth.tooManyRequests": "Too many attempts. Please wait a moment.",
    "auth.weakPassword": "Password must be at least 6 characters",
    "auth.invalidEmail": "Invalid email address",
    "auth.userAlreadyExists": "This email is already registered. Try logging in or reset your password.",
    "auth.accountBlocked": "Your account has been blocked. Contact an administrator.",
    "auth.confirmPassword": "Confirm Password",
    "auth.passwordMismatch": "Passwords do not match",

    // Admin Panel
    "adminPanel.title": "Admin Panel",
    "adminPanel.users": "users",
    "adminPanel.addUser": "Add User",
    "adminPanel.addUserTitle": "Add New User",
    "adminPanel.addUserDesc": "Create a new staff account.",
    "adminPanel.name": "Name",
    "adminPanel.role": "Role",
    "adminPanel.status": "Status",
    "adminPanel.actions": "Actions",
    "adminPanel.staff": "Staff",
    "adminPanel.blocked": "Blocked",
    "adminPanel.active": "Active",
    "adminPanel.delete": "Delete",
    "adminPanel.deleteConfirmTitle": "Delete User",
    "adminPanel.deleteConfirmDesc": "Are you sure you want to delete {name}? This action cannot be undone.",
    "adminPanel.userAdded": "User added successfully",
    "adminPanel.userDeleted": "User deleted successfully",
    "adminPanel.userBlocked": "User blocked",
    "adminPanel.userUnblocked": "User unblocked",
    "admin.allUsers": "All Users",
    "footer.rights": "All Rights Reserved",
    "adminPanel.fetchError": "Failed to load users",
    "adminPanel.addError": "Failed to add user",
    "adminPanel.deleteError": "Failed to delete user",
    "adminPanel.blockError": "Operation failed",
    "adminPanel.fillAllFields": "Please fill all fields",
    "adminPanel.adminAssigned": "User assigned as admin",
    "adminPanel.adminRemoved": "Admin role removed",
    "adminPanel.userOpened": "User unblocked",
    "error.404": "Oops! Page not found",
    "error.returnHome": "Return to Home",

    // Activity Card & Form
    "activity.workReport": "WORK REPORT",
    "activity.preparedBy": "Prepared by",
    "activity.supervisor": "Supervisor (Uitvoerder)",
    "activity.period": "Period",
    "activity.day": "Day",
    "activity.description": "Description",
    "activity.extraWork": "Extra Work (Meerwerk)",
    "activity.location": "Location / Site",
    "activity.hours": "Hours",
    "activity.details": "Work Details",
    "activity.gallery": "Photo Gallery",
    "activity.subtitle": "Weekly work summary journal",
    "activity.send": "SEND",
    "activity.edit": "EDIT",
    "activity.delete": "DELETE",
    "activity.total": "Total",
    "activity.save": "Save",
    "activity.saved": "Saved",
    "activity.saving": "Saving...",
    "activity.add": "Add",
    "activity.photo": "PHOTO",
    "activity.submit": "OPSLAAN",
    "activity.locationDetected": "Location Detected",
    "activity.totalRecords": "Total {count} Records",
    "activity.week": "Week",
    "activity.locationPermissionRequired": "Location permission denied. Please enable your device's location (GPS) and grant location permission to this site in your browser settings.",
  },
  nl: {
    // Auth
    "auth.login": "Log in op uw account",
    "auth.signup": "Maak een nieuw account aan",
    "auth.fullName": "Volledige Naam",
    "auth.fullNamePlaceholder": "Uw Volledige Naam",
    "auth.email": "E-mail",
    "auth.emailPlaceholder": "voorbeeld@email.com",
    "auth.password": "Wachtwoord",
    "auth.loginButton": "Inloggen",
    "auth.signupButton": "Registreren",
    "auth.noAccount": "Geen account? Registreer",
    "auth.hasAccount": "Heeft u al een account? Inloggen",
    "auth.signupSuccess": "Registratie succesvol",
    "auth.loginSuccess": "Inloggen geslaagd",
    "auth.welcome": "Welkom",
    "auth.lang_code": "nl",
    "auth.checkEmail": "Controleer uw inbox om uw e-mailadres te verifiëren.",
    "auth.error": "Fout",
    "landing.title": "Gegevens uit het Veld",
    "landing.highlight": "Uw Rapport in Eén Klik",
    "landing.badge": "Digitaal Rapportagesysteem",
    "landing.description": "EA APP stelt u in staat om uw dagelijkse werkuren, personeel en meerwerk digitaal vast te leggen vanaf de locatie. Het berekent automatisch de gegevens en zet ze direct om in professionele wekelijkse PDF-rapporten.",
    "landing.secure": "Veilige Gegevensopslag",
    "landing.access": "Overal Toegang",
    "feature.1.title": "Eenvoudige Gegevensinvoer",
    "feature.1.desc": "Log dagelijkse diensten, locaties en uw teamleden in enkele seconden.",
    "feature.2.title": "Geautomatiseerde PDF",
    "feature.2.desc": "Uw gegevens worden direct gegenereerd als officiële PDF-rapporten, volledig in het Nederlands.",
    "feature.3.title": "Cloud Opslag",
    "feature.3.desc": "Vergeet verwijderde records of verloren bestanden. Al uw rapporten en foto's worden veilig bewaard.",

    // Index
    "index.admin": "Beheerder",
    "index.activities": "activiteiten",
    "index.new": "Nieuw",
    "index.newActivity": "Nieuwe Weekactiviteit",



    // Activity Form
    "form.whatDidYouDo": "Wat heb je gedaan?",
    "form.descriptionPlaceholder": "Beschrijf uw werk...",
    "form.location": "Locatie",
    "form.locationPlaceholder": "bijv. Hoofdkantoor, Amsterdam",
    "form.date": "Week Beginnend",
    "form.selectDate": "Selecteer datum",
    "form.photos": "Foto's",
    "form.photo": "Foto",
    "form.upload": "Uploaden",
    "form.addActivity": "Weekactiviteit Toevoegen",
    "form.weeklyWork": "Wekelijks Werk",
    "form.hours": "Uren",
    "form.hoursPlaceholder": "Uren",
    "form.totalHours": "Totaal Uren",
    "form.teammates": "Teamgenoten",
    "form.person": "Persoon",
    "form.personName": "Naam",
    "form.addPerson": "Persoon Toevoegen",
    "form.meerwerk": "Meerwerk",
    "form.meerwerkPlaceholder": "Meerwerk indien van toepassing...",

    // Days
    "days.monday": "Maandag",
    "days.tuesday": "Dinsdag",
    "days.wednesday": "Woensdag",
    "days.thursday": "Donderdag",
    "days.friday": "Vrijdag",
    "days.saturday": "Zaterdag",
    "days.workPlaceholder": "Wat heb je deze dag gedaan?",

    // Activity List
    "list.loading": "Activiteiten laden...",
    "list.empty": "Nog geen activiteiten",
    "list.addFirst": "Voeg hierboven uw eerste activiteit toe",
    "list.photos": "foto's",
    "list.photo": "Foto",
    "list.weekOf": "Week van",
    "list.hoursShort": "uur",
    "list.translating": "Bezig met vertalen...",

    // Invoice
    "invoice.title": "Wekelijks Werk",
    "invoice.generateInvoice": "Rapport Genereren",
    "invoice.weeklyReport": "Werkrapport",
    "invoice.employee": "Opsteller",
    "invoice.period": "Periode",
    "invoice.day": "Dag",
    "invoice.description": "Beschrijving",
    "invoice.location": "Locatie",
    "invoice.hours": "Uren",
    "invoice.total": "Totaal",
    "invoice.print": "Afdrukken",
    "invoice.send": "Versturen",
    "invoice.saveToPhone": "Opslaan op Telefoon",
    "invoice.sendEmail": "Verzenden via E-mail",
    "invoice.sendWhatsApp": "Verzenden via WhatsApp",
    "invoice.pdfDownloaded": "PDF-bestand gedownload, voeg het toe aan de e-mail.",

    // Edit
    "edit.title": "Activiteit Bewerken",
    "edit.save": "Opslaan",
    "edit.cancel": "Annuleren",
    "edit.success": "Activiteit bijgewerkt",
    "invoice.close": "Sluiten",

    // Translate
    "translate.button": "Vertalen",
    "translate.translating": "Bezig met vertalen...",
    "translate.error": "Vertaling mislukt",
    "translate.rateLimited": "Te veel verzoeken. Even wachten.",
    "translate.paymentRequired": "Credits vereist.",

    // Forgot Password
    "auth.forgotPassword": "Wachtwoord vergeten?",
    "auth.sendResetLink": "Resetlink Sturen",
    "auth.backToLogin": "Terug naar inloggen",
    "auth.resetEmailSent": "E-mail verzonden",
    "auth.checkEmailReset": "Controleer uw inbox voor de wachtwoord reset link.",
    "auth.newPassword": "Nieuw Wachtwoord",
    "auth.confirmNewPassword": "Nieuw Wachtwoord Bevestigen",
    "auth.setNewPassword": "Nieuw Wachtwoord Instellen",
    "auth.updatePasswordButton": "Wachtwoord Bijwerken",
    "auth.passwordUpdated": "Wachtwoord succesvol bijgewerkt",
    "auth.passwordUpdateError": "Wachtwoord bijwerken mislukt",

    // Error messages
    "auth.invalidCredentials": "Ongeldige e-mail of wachtwoord",
    "auth.userNotFound": "Geen gebruiker gevonden met dit e-mailadres",
    "auth.emailNotConfirmed": "Uw e-mail is nog niet geverifieerd. Controleer uw inbox.",
    "auth.tooManyRequests": "Te veel pogingen. Wacht even.",
    "auth.weakPassword": "Wachtwoord moet minimaal 6 tekens bevatten",
    "auth.invalidEmail": "Ongeldig e-mailadres",
    "auth.userAlreadyExists": "Dit e-mailadres is al geregistreerd. Probeer in te loggen of reset uw wachtwoord.",
    "auth.accountBlocked": "Uw account is geblokkeerd. Neem contact op met een beheerder.",
    "auth.confirmPassword": "Wachtwoord Bevestigen",
    "auth.passwordMismatch": "Wachtwoorden komen niet overeen",

    // Admin Panel
    "adminPanel.title": "Beheerderspaneel",
    "adminPanel.users": "gebruikers",
    "adminPanel.addUser": "Gebruiker Toevoegen",
    "adminPanel.addUserTitle": "Nieuwe Gebruiker Toevoegen",
    "adminPanel.addUserDesc": "Maak een nieuw personeelsaccount aan.",
    "adminPanel.name": "Naam",
    "adminPanel.role": "Rol",
    "adminPanel.status": "Status",
    "adminPanel.actions": "Acties",
    "adminPanel.staff": "Personeel",
    "adminPanel.blocked": "Geblokkeerd",
    "adminPanel.active": "Actief",
    "adminPanel.delete": "Verwijderen",
    "adminPanel.deleteConfirmTitle": "Gebruiker Verwijderen",
    "adminPanel.deleteConfirmDesc":
      "Weet u zeker dat u {name} wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.",
    "adminPanel.userAdded": "Gebruiker succesvol toegevoegd",
    "adminPanel.userDeleted": "Gebruiker succesvol verwijderd",
    "adminPanel.userBlocked": "Gebruiker geblokkeerd",
    "adminPanel.userUnblocked": "Gebruiker gedeblokkeerd",
    "admin.allUsers": "Alle Gebruikers",
    "footer.rights": "Alle Rechten Voorbehouden",
    "adminPanel.fetchError": "Gebruikers konden niet worden geladen",
    "adminPanel.addError": "Gebruiker kon niet worden toegevoegd",
    "adminPanel.deleteError": "Gebruiker kon niet worden verwijderd",
    "adminPanel.blockError": "Bewerking mislukt",
    "adminPanel.fillAllFields": "Vul alle velden in",
    "adminPanel.adminAssigned": "Gebruiker toegewezen als admin",
    "adminPanel.adminRemoved": "Admin-rol verwijderd",
    "adminPanel.userOpened": "Gebruiker gedeblokkeerd",
    "error.404": "Oeps! Pagina niet gevonden",
    "error.returnHome": "Terug naar Home",

    // Activity Card & Form
    "activity.workReport": "WERKRAPPORT",
    "activity.preparedBy": "Opsteller",
    "activity.supervisor": "Uitvoerder",
    "activity.period": "Periode",
    "activity.day": "Dag",
    "activity.description": "Beschrijving",
    "activity.extraWork": "Meerwerk (Extra)",
    "activity.location": "Locatie / Site",
    "activity.hours": "Uren",
    "activity.details": "Werk Details",
    "activity.gallery": "Foto Galerij",
    "activity.subtitle": "Wekelijks werkoverzicht logboek",
    "activity.send": "VERSTUREN",
    "activity.edit": "BEWERKEN",
    "activity.delete": "VERWIJDEREN",
    "activity.total": "Totaal",
    "activity.save": "Opslaan",
    "activity.saved": "Opgeslagen",
    "activity.saving": "Bezig met opslaan...",
    "activity.add": "Toevoegen",
    "activity.photo": "FOTO",
    "activity.submit": "OPSLAAN",
    "activity.locationDetected": "Locatie Vastgesteld",
    "activity.totalRecords": "Totaal {count} Records",
    "activity.week": "Week",
    "activity.locationPermissionRequired": "Locatietoestemming geweigerd. Schakel de locatie van uw apparaat (GPS) in en verleen locatietoestemming aan deze site in uw browserinstellingen.",
  },
  ar: {
    // Auth
    "auth.login": "تسجيل الدخول إلى حسابك",
    "auth.signup": "إنشاء حساب جديد",
    "auth.fullName": "الاسم الكامل",
    "auth.fullNamePlaceholder": "اسمك الكامل",
    "auth.email": "البريد الإلكتروني",
    "auth.emailPlaceholder": "example@email.com",
    "auth.password": "كلمة المرور",
    "auth.loginButton": "تسجيل الدخول",
    "auth.signupButton": "إنشاء حساب",
    "auth.noAccount": "ليس لديك حساب؟ سجل الآن",
    "auth.hasAccount": "لديك حساب بالفعل؟ تسجيل الدخول",
    "auth.signupSuccess": "تم التسجيل بنجاح",
    "auth.loginSuccess": "تم تسجيل الدخول بنajاح",
    "auth.welcome": "مرحباً بك",
    "auth.lang_code": "ar",
    "auth.checkEmail": "تحقق من بريدك الإلكتروني للتحقق من عنوانك.",
    "auth.error": "خطأ",
    "landing.title": "بيانات من الميدان",
    "landing.highlight": "تقريرك بنقرة واحدة",
    "landing.badge": "نظام الإبلاغ الرقمي",
    "landing.description": "يتيح لك تطبيق EA تسجيل ساعات عملك اليومية وموظفيك والعمل الإضافي (meerwerk) رقميًا مباشرة من الموقع. يقوم تلقائيًا بحساب البيانات وتحويلها فورًا إلى تقارير PDF أسبوعية احترافية.",
    "landing.secure": "تخزين بيانات آمن",
    "landing.access": "الوصول من أي مكان",
    "feature.1.title": "إدخال بيانات سهل",
    "feature.1.desc": "قم بتسجيل الورديات اليومية والمواقع وأعضاء فريقك في ثوانٍ.",
    "feature.2.title": "PDF تلقائي",
    "feature.2.desc": "يتم إنشاء بياناتك على الفور كتقارير PDF رسمية، باللغة الهولندية بالكامل.",
    "feature.3.title": "تخزين سحابي",
    "feature.3.desc": "انس أمر السجلات المحذوفة أو الملفات المفقودة. يتم تخزين جميع تقاريرك وصورك بأمان.",

    // Index
    "index.admin": "مدير",
    "index.activities": "نشاط",
    "index.new": "جديد",
    "index.newActivity": "نشاط أسبوعي جديد",



    // Activity Form
    "form.whatDidYouDo": "ماذا فعلت؟",
    "form.descriptionPlaceholder": "صف عملك...",
    "form.location": "الموقع",
    "form.locationPlaceholder": "مثال: المكتب الرئيسي، أمستردام",
    "form.date": "بداية الأسبوع",
    "form.selectDate": "اختر التاريخ",
    "form.photos": "الصور",
    "form.photo": "صورة",
    "form.upload": "رفع",
    "form.addActivity": "إضافة نشاط أسبوعي",
    "form.weeklyWork": "العمل الأسبوعي",
    "form.hours": "ساعات",
    "form.hoursPlaceholder": "ساعات",
    "form.totalHours": "إجمالي الساعات",
    "form.teammates": "زملاء العمل",
    "form.person": "شخص",
    "form.personName": "الاسم",
    "form.addPerson": "إضافة شخص",
    "form.meerwerk": "عمل إضافي",
    "form.meerwerkPlaceholder": "عمل إضافي إن وجد...",

    // Days
    "days.monday": "الإثنين",
    "days.tuesday": "الثلاثاء",
    "days.wednesday": "الأربعاء",
    "days.thursday": "الخميس",
    "days.friday": "الجمعة",
    "days.saturday": "السبت",
    "days.workPlaceholder": "ماذا فعلت في هذا اليوم؟",

    // Activity List
    "list.loading": "جاري تحميل الأنشطة...",
    "list.empty": "لا توجد أنشطة بعد",
    "list.addFirst": "أضف نشاطك الأول من الأعلى",
    "list.photos": "صور",
    "list.photo": "صورة",
    "list.weekOf": "أسبوع",
    "list.hoursShort": "ساعة",
    "list.translating": "جاري الترجمة...",

    // Invoice
    "invoice.title": "العمل الأسبوعي",
    "invoice.generateInvoice": "إنشاء تقرير",
    "invoice.weeklyReport": "تقرير العمل الأسبوعي",
    "invoice.employee": "الموظف",
    "invoice.period": "الفترة",
    "invoice.day": "اليوم",
    "invoice.description": "الوصف",
    "invoice.location": "الموقع",
    "invoice.hours": "ساعات",
    "invoice.total": "المجموع",
    "invoice.print": "طباعة",
    "invoice.send": "إرسال",
    "invoice.saveToPhone": "حفظ على الهاتف",
    "invoice.sendEmail": "إرسال بالبريد الإلكتروني",
    "invoice.sendWhatsApp": "إرسال عبر واتساب",
    "invoice.pdfDownloaded": "تم تنزيل ملف PDF، يرجى إرفاقه بالبريد الإلكتروني.",

    // Edit
    "edit.title": "تعديل النشاط",
    "edit.save": "حفظ",
    "edit.cancel": "إلغاء",
    "edit.success": "تم تحديث النشاط",
    "invoice.close": "إغلاق",

    // Translate
    "translate.button": "ترجمة",
    "translate.translating": "جاري الترجمة...",
    "translate.error": "فشلت الترجمة",
    "translate.rateLimited": "طلبات كثيرة. يرجى الانتظار.",
    "translate.paymentRequired": "رصيد مطلوب.",

    // Forgot Password
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.sendResetLink": "إرسال رابط إعادة التعيين",
    "auth.backToLogin": "العودة لتسجيل الدخول",
    "auth.resetEmailSent": "تم إرسال البريد الإلكتروني",
    "auth.checkEmailReset": "تحقق من بريدك للحصول على رابط إعادة تعيين كلمة المرور.",
    "auth.newPassword": "كلمة المرور الجديدة",
    "auth.confirmNewPassword": "تأكيد كلمة المرور الجديدة",
    "auth.setNewPassword": "تعيين كلمة مرور جديدة",
    "auth.updatePasswordButton": "تحديث كلمة المرور",
    "auth.passwordUpdated": "تم تحديث كلمة المرور بنجاح",
    "auth.passwordUpdateError": "فشل تحديث كلمة المرور",

    // Error messages
    "auth.invalidCredentials": "بريد إلكتروني أو كلمة مرور غير صالحة",
    "auth.userNotFound": "لم يتم العثور على مستخدم بهذا البريد الإلكتروني",
    "auth.emailNotConfirmed": "لم يتم التحقق من بريدك الإلكتروني بعد. يرجى التحقق من صندوق الوارد.",
    "auth.tooManyRequests": "محاولات كثيرة جداً. يرجى الانتظار قليلاً.",
    "auth.weakPassword": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    "auth.invalidEmail": "عنوان بريد إلكتروني غير صالح",
    "auth.userAlreadyExists": "هذا البريد الإلكتروني مسجل بالفعل. حاول تسجيل الدخول أو إعادة تعيين كلمة المرور.",
    "auth.accountBlocked": "تم حظر حسابك. اتصل بالمسؤول.",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.passwordMismatch": "كلمات المرور غير متطابقة",

    // Admin Panel
    "adminPanel.title": "لوحة الإدارة",
    "adminPanel.users": "مستخدم",
    "adminPanel.addUser": "إضافة مستخدم",
    "adminPanel.addUserTitle": "إضافة مستخدم جديد",
    "adminPanel.addUserDesc": "إنشاء حساب موظف جديد.",
    "adminPanel.name": "الاسم",
    "adminPanel.role": "الدور",
    "adminPanel.status": "الحالة",
    "adminPanel.actions": "الإجراءات",
    "adminPanel.staff": "موظف",
    "adminPanel.blocked": "محظور",
    "adminPanel.active": "نشط",
    "adminPanel.delete": "حذف",
    "adminPanel.deleteConfirmTitle": "حذف المستخدم",
    "adminPanel.deleteConfirmDesc": "هل أنت متأكد أنك تريد حذف {name}؟ لا يمكن التراجع عن هذا الإجراء.",
    "adminPanel.userAdded": "تمت إضافة المستخدم بنجاح",
    "adminPanel.userDeleted": "تم حذف المستخدم بنجاح",
    "adminPanel.userBlocked": "تم حظر المستخدم",
    "adminPanel.userUnblocked": "تم إلغاء حظر المستخدم",
    "admin.allUsers": "جميع المستخدمين",
    "footer.rights": "جميع الحقوق محفوظة",
    "adminPanel.fetchError": "فشل تحميل المستخدمين",
    "adminPanel.addError": "فشل إضافة مستخدم",
    "adminPanel.deleteError": "فشل حذف مستخدم",
    "adminPanel.blockError": "فشلت العملية",
    "adminPanel.fillAllFields": "يرجى ملء جميع الحقول",
    "adminPanel.adminAssigned": "تم تعيين المستخدم كمدير",
    "adminPanel.adminRemoved": "تمت إزالة دور المدير",
    "adminPanel.userOpened": "تم إلغاء حظر المستخدم",
    "error.404": "عذراً! الصفحة غير موجودة",
    "error.returnHome": "العودة إلى الصفحة الرئيسية",

    // Activity Card & Form
    "activity.workReport": "تقرير العمل",
    "activity.preparedBy": "تم الإعداد بواسطة",
    "activity.supervisor": "المشرف (Uitvoerder)",
    "activity.period": "الفترة",
    "activity.day": "اليوم",
    "activity.description": "الوصف",
    "activity.extraWork": "عمل إضافي",
    "activity.location": "الموقع",
    "activity.hours": "ساعة",
    "activity.send": "إرسال",
    "activity.edit": "تعديل",
    "activity.delete": "حذف",
    "activity.total": "المجموع",
    "activity.save": "حفظ",
    "activity.saved": "تم الحفظ",
    "activity.saving": "جاري الحفظ...",
    "activity.add": "إضافة",
    "activity.photo": "صورة",
    "activity.submit": "إرسال التقرير",
    "activity.locationDetected": "تم تحديد الموقع",
    "activity.totalRecords": "إجمالي {count} سجلات",
    "activity.week": "أسبوع",
    "activity.locationPermissionRequired": "تم رفض إذن الموقع. يرجى تمكين موقع جهازك (GPS) ومنح إذن الموقع لهذا الموقع في إعدادات المتصفح.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "nl";
  });

  const isRTL = language === "ar";

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
  }, [language, isRTL]);

  return <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
